### ISSUE TITLE
Add reference to stages in Scenarios page

### ISSUE THREAD

**Issue by nicolek6** [k6io/docs#167]
### Problem
Currently, stages are discussed in the [Options page](https://k6.io/docs/using-k6/options), which is not where I'd expect to find them. When attempting to replicate a load profile, I went straight for the Scenarios page.

### Suggested solution
I think it would be worth mentioning and linking to our [documentation on Stages](https://k6.io/docs/using-k6/options#stages) from the [Scenarios page](https://k6.io/docs/using-k6/scenarios) to make it easier to find.

**Comment by ppcano** [comment]
Agree. 

Thinking loudly:

I would also consider improving the `stages` docs earlier, because `Scenarios` is further down and considered an advanced topic. 

We comment `stages` on [Getting Started / Running k6](https://k6.io/docs/getting-started/running-k6#stages-ramping-up-down-vus). But this might not be obvious.

We could consider splitting the Options list in different "context". Or separate the "load" settings into a separate page.

**Comment by MStoykov** [comment]
I would also argue that we should not recommend using stages ... anymore but instead recommend arrival rate executors. I would argue that the additional 10-20 characters that need to be copied between the `stages`/`ramping-vus` and the `ramping-arrival-rate` executors is well worth it given the difference in how they perform. 

Arguably there should also be a lengthy, in-depth, and full of examples explanation on why arrival rate is better and why you should probably not use anything else.

**Comment by MStoykov** [comment]
@simskij https://github.com/loadimpact/k6-docs/issues/175
